version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/apps/dashboard/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  # Serverless dependencies
  - package-ecosystem: "npm"
    directory: "/serverless/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
