version: "1.0"

services:
  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/taly
      NODE_ENV: development
      JWT_SECRET: dev_jwt_secret
      JWT_EXPIRES_IN: 1d
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/dashboard:/app
      - /app/node_modules
    environment:
      API_URL: http://localhost:4000
      NODE_ENV: development
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: taly_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taly
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
