version: '1.0'

services:
  # Serviço Backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/taly
      NODE_ENV: development
    depends_on:
      - db

  # Serviço Frontend
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:4000
      NODE_ENV: development
    depends_on:
      - backend

  # Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: taly_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taly
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
