service: taly-send-email

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1  # Replace with your AWS region
  environment:
    NODE_ENV: ${opt:stage, 'dev'}  # Use stage variable, default to 'dev'
    # ... other environment variables (e.g., email API keys)
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*" # Restrict to specific resources if possible

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - sns: # example of event trigger.
          arn:  # the arn for a sns topic
          topicName: your-topic
      #- http:  # example of http endpoint trigger.
      #    path: /send-email
      #    method: post
      #    cors: true

plugins:
  - serverless-offline # For local development
  - serverless-plugin-typescript