# Base development image
FROM node:18-alpine AS development

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package*.json ./

# Install build dependencies
RUN apk add --no-cache python3 make g++ && npm install

# Copy app source
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the app
FROM development AS build

RUN npm run build

# Final production image
FROM node:18-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy built app
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY prisma ./prisma

# Expose port
EXPOSE 3000

# Start the app
CMD ["node", "dist/main"]
