import { z } from "zod";

export const PaymentSchema = z.object({
	id: z.string().optional(), // Will be generated by backend for new payments
	userId: z.string(),
	amount: z.number().positive(),
	currency: z.string().default("USD"),
	status: z.enum(["pending", "completed", "failed", "cancelled"]),
	paymentMethod: z.enum([
		"credit_card",
		"debit_card",
		"paypal",
		"bank_transfer",
	]),
	paymentDate: z.string().or(z.date()).optional(),
	description: z.string().optional(),
	metadata: z.record(z.unknown()).optional(),
	createdAt: z.string().or(z.date()).optional(),
	updatedAt: z.string().or(z.date()).optional(),
});

export type Payment = z.infer<typeof PaymentSchema>;
