service: cleanup-temp-files

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment:
    TEMP_BUCKET_NAME: ${env:TEMP_BUCKET_NAME}

functions:
  cleanupTempFiles:
    handler: handler.cleanupTempFiles
    events:
      - schedule:
          rate: rate(3 day) # Executa a cada 24 horas
          enabled: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:ListBucket
          - s3:GetObject
          - s3:DeleteObject
        Resource:
          - arn:aws:s3:::${env:TEMP_BUCKET_NAME}
          - arn:aws:s3:::${env:TEMP_BUCKET_NAME}/*

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
