name: Database Migration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  database-migration:
    name: Apply Database Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.0

      - name: Install Dependencies
        run: pnpm install
        working-directory: backend/

      - name: Setup Prisma
        run: pnpm add -D prisma@latest
        working-directory: backend/

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm prisma migrate deploy
        working-directory: backend/

      - name: Validate Database Schema (Optional)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm prisma validate
        working-directory: backend/

      - name: Seed Database (Optional for Dev/Stage)
        if: github.ref != 'refs/heads/main'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node prisma/seed.ts
        working-directory: backend/

      - name: Notify Team on Failure
        if: failure()
        run: |
          echo "⚠️ Database migration failed. Check logs: ${{ github.run_id }}"
