name: Database Migration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  database-migration:
    name: Apply Database Migrations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: backend/

      - name: Setup Prisma
        run: npm install prisma@latest --save-dev
        working-directory: backend/

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
        working-directory: backend/

      - name: Test Database Schema (Optional)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma validate
        working-directory: backend/

      - name: Seed Database (Optional for Dev/Stage Environments)
        if: github.ref != 'refs/heads/main'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node prisma/seed.js
        working-directory: backend/

      - name: Notify Team (Optional)
        if: failure()
        run: echo "Database migration failed. Please investigate."
