name: Frontend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.0

      - name: Install Dependencies
        run: pnpm install
        working-directory: ./apps/dashboard/

      - name: Lint Code
        run: pnpm run lint
        working-directory: ./apps/dashboard/

      - name: Run Unit Tests
        run: pnpm run test:ci
        working-directory: ./apps/dashboard/

      - name: Build Frontend
        run: pnpm run build
        working-directory: ./apps/dashboard/

      - name: Upload Build Artifacts (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-build
          path: ./apps/dashboard/.next/

      - name: Notify Team on Failure
        if: failure()
        run: |
          echo "❌ Frontend CI failed. Check logs: ${{ github.run_id }}"
