name: Nightly Build and Test

on:
  schedule:
    - cron: "0 2 * * *" # D 02:00 UTC

jobs:
  nightly-build:
    name: Nightly Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.0

      - name: Install Dependencies (Frontend)
        run: pnpm install
        working-directory: ./apps/dashboard/

      - name: Install Dependencies (Backend)
        run: pnpm install
        working-directory: ./backend/

      - name: Lint Frontend Code
        run: pnpm run lint
        working-directory: ./apps/dashboard/

      - name: Lint Backend Code
        run: pnpm run lint
        working-directory: ./backend/

      - name: Run Frontend Tests
        run: pnpm run test:ci
        working-directory: ./apps/dashboard/

      - name: Run Backend Tests
        run: pnpm run test:ci
        working-directory: ./backend/

      - name: Build Frontend
        run: pnpm run build
        working-directory: ./apps/dashboard/

      - name: Build Backend
        run: pnpm run build
        working-directory: ./backend/

      - name: E2E Tests
        run: pnpm run test:e2e
        working-directory: ./tests/e2e/

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: nightly-test-reports
          path: ./tests/reports/

      - name: Notify Team on Failure
        if: failure()
        run: |
          echo "❌ Frontend CI failed. Check logs: ${{ github.run_id }}"
