name: Serverless CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  serverless-ci:
    name: Serverless CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Dependencies (Send Email Function)
        run: npm install
        working-directory: C:/taly/dir-taly/taly/serverless/send-email/

      - name: Install Dependencies (Process Payment Function)
        run: npm install
        working-directory: C:/taly/dir-taly/taly/serverless/process-payment/

      - name: Install Dependencies (Generate Reports Function)
        run: npm install
        working-directory: C:/taly/dir-taly/taly/serverless/generate-reports/

      - name: Lint Functions
        run: |
          npm run lint
          npm run lint
          npm run lint
        working-directory: C:/taly/dir-taly/taly/serverless/

      - name: Run Unit Tests
        run: npm run test:ci
        working-directory: C:/taly/dir-taly/taly/serverless/

      #   - name: Deploy to Staging
      #     if: github.ref == 'refs/heads/main'
      #     env:
      #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #       AWS_REGION: us-east-1
      #     run: serverless deploy --stage staging
      #     working-directory: C:/taly/dir-taly/taly/serverless/

      - name: Notify Team on Failure
        if: failure()
        run: echo "Serverless CI failed. Please check the logs."
